[project]
name = "LiDAR-RT"
version = "0.1.0"
description = "LiDAR-RT: Gaussian-based Ray Tracing for Dynamic LiDAR Re-simulation"
authors = [{ name = "cxzhou35", email = "cxzhou35@zju.edu.cn" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10,<3.13"
dependencies = [
    "torch>=2.3.0,<2.4.0",
    "torchvision>=0.18.0,<0.19.0",
    "torchaudio>=2.3.0,<2.4.0",
    "numpy>=2.0.0",
    "open3d>=0.19.0",
    "opencv-python>=4.10.0",
    "Pillow>=10.0.0",
    "pyquaternion>=0.9.9",
    "ruamel.yaml>=0.19.0",
    "tqdm>=4.60.0",
    "matplotlib>=3.9.0",
    "rerun-sdk>=0.27.0",
    "lpips>=0.1.4",
    "imageio[ffmpeg]>=2.30.0",
    "scikit-image>=0.25.0",
    "tensorboard>=2.19.0",
    "plyfile>=1.0.0",
    "kornia>=0.8.0",
    "icosphere>=0.2.0",
    "tensorboardX>=2.6.0",
    "termcolor>=2.0.0",
    "t4-devkit>=0.7.1",
    "wandb>=0.16.0",
    "simple_knn",
    "diff_lidar_tracer",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.uv]
find-links = ["https://download.pytorch.org/whl/cu121"]
no-build-isolation-package = ["simple_knn", "diff_lidar_tracer"]

[tool.uv.sources]
t4-devkit = { git = "https://github.com/tier4/t4-devkit.git", rev = "4da7fd576a53165b3ce7090c45af4ce85eaaf80c" }
simple_knn = { path = "submodules/simple-knn" }
diff_lidar_tracer = { path = "submodules/diff-lidar-tracer" }

[tool.uv.extra-build-variables]
simple_knn = { TORCH_CUDA_ARCH_LIST = "8.0;8.6;8.9;9.0" }
diff_lidar_tracer = { TORCH_CUDA_ARCH_LIST = "8.0;8.6;8.9;9.0" }

[project.urls]
homepage = "https://zju3dv.github.io/lidar-rt"

[tool.pyright]
exclude = ["**/__pycache__", "data", "output"]

reportMissingImports = "warning"
reportMissingTypeStubs = false
reportPrivateImportUsage = false

[tool.isort]
profile = "hug"
skip = [".gitignore"]
length_sort = true
lines_between_sections = 0
lines_after_imports = 1
